### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by egesarisac** [vkovic/laravel-db-redirector#1]
Can you add Laravel 5.8 support?

Thanks

**Comment by vkovic** [comment]
Hi @egesarisac, please give it a try now and tell me if everything is ok

**Comment by egesarisac** [comment]
I've got an error while migrating but it is working. 

> Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `redirect_rule
> s` add unique `redirect_rules_origin_unique`(`origin`))

**Comment by vkovic** [comment]
Ok, glad that it worked.

Regarding the problem i think i found [the cause](https://laravel-news.com/laravel-5-4-key-too-long-error).

I'm planning to improve this package and made it event easier for usage, so stay tuned 📻 #
