### ISSUE TITLE
404 Redirects

### ISSUE THREAD

**Issue by egesarisac** [vkovic/laravel-db-redirector#3]
I've inserted a non-existent link to redirect rules, when i visit the link it redirects me to the 404 page directly.Is there a way to run db-redirector before laravel's exception handler?

**Comment by vkovic** [comment]
Which version of PHP are you using, is it maybe 7.3 ?

**Comment by egesarisac** [comment]
My PHP version is 7.1.29
Laravel Framework 5.8.29

**Comment by vkovic** [comment]
Hmmm, i just test it with the project i'm maintaining (it's on Laravel 5.7) and everything works as expected even if it's redirecting from non existing page.

Can you ensure that package middleware is in the right place - it must be manually added to:

```php
// File: app/Http/Kernel.php

// ...

protected $middleware = [
    // ...
    \Vkovic\LaravelDbRedirector\Http\Middleware\DbRedirectorMiddleware::class
];
```

**Comment by egesarisac** [comment]
It redirects from non-existing page if it is inserted to the database without full URL.

Ex:  Origin "http://github.com/vkovic" doesnt redirect to the destination while "/vkovic" does.

**Comment by vkovic** [comment]
Ok, this is actually not part of intended functionality. As you can see in [README.md](https://github.com/vkovic/laravel-db-redirector#usage-simple-examples) all examples are using relative urls (e.g. `/one/two`). 

Most of the projects are using relative urls when writing to the database. Using absolute urls is bad from few perspectives, like migrating website to different domain, developing website in multiple environments (like local, dev, integration etc.).

Having this on mind I decided to stick to relative urls only. 

So if the project allows, please stick to them.
